import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import initSqlJs from 'sql.js';
import { COURSE } from './courseData.js';
import './styles.css';

const LS_USER='sql_pwa_user_v3', LS_AUTH='sql_pwa_auth_v3', LS_REQUESTS='sql_pwa_access_requests_v3', LS_PROGRESS='sql_pwa_progress_v3', LS_THEME='sql_pwa_theme_v3', LS_FONT='sql_pwa_font_v3';
const DEFAULT_ADMIN={username:'admin',password:'admin123',role:'admin',firstLogin:true,name:'Administrador'};
function readJson(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function normalizeSql(s){return (s||'').trim().replace(/;+\s*$/,'')}
function isSafeSelect(sql){const s=normalizeSql(sql).toLowerCase();return !!s&&/^(select|with)\b/i.test(s)&&!/(^|\s)(insert|update|delete|drop|alter|create|truncate|replace|attach|detach|pragma|vacuum|reindex)\b/i.test(s)}
function getFirstResult(res){return !res.length?{columns:[],rows:[]}:{columns:res[0].columns,rows:res[0].values}}
function runQueryOnFreshDb(SQL,dbSqlText,sql){const clean=normalizeSql(sql);if(!SQL||!dbSqlText)throw new Error('Banco ainda não carregado.');if(!isSafeSelect(clean))throw new Error('Use apenas SELECT ou WITH. Escrita no banco fica bloqueada.');let db=null;try{db=new SQL.Database();db.run(dbSqlText);return getFirstResult(db.exec(clean))}finally{if(db)db.close()}}
function makeId(m,e){return `${m}::${e}`}
function normUser(s){return (s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9.]/g,'.').replace(/\.+/g,'.').replace(/^\.|\.$/g,'')}
function randPass(){return 'SQL'+Math.random().toString(36).slice(2,6).toUpperCase()+Math.floor(100+Math.random()*900)}
function getAuth(){const a=readJson(LS_AUTH,null);if(a?.users)return a;const base={users:{[DEFAULT_ADMIN.username]:DEFAULT_ADMIN}};localStorage.setItem(LS_AUTH,JSON.stringify(base));return base}
function saveAuth(a){localStorage.setItem(LS_AUTH,JSON.stringify(a))}
function saveProgress(p){localStorage.setItem(LS_PROGRESS,JSON.stringify(p))}
async function notifyTelegram(text){const token=import.meta.env.VITE_TELEGRAM_BOT_TOKEN||'',chatId=import.meta.env.VITE_TELEGRAM_CHAT_ID||'';if(!token||!chatId)throw new Error('Telegram não configurado no .env.');const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text})});if(!r.ok)throw new Error('Falha no Telegram: HTTP '+r.status)}
function pct(n,d){return Math.round((n/Math.max(d,1))*100)}

function Login({onLogin}){const[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[pass,setPass]=useState(''),[first,setFirst]=useState(''),[last,setLast]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState('');function submit(e){e.preventDefault();setErr('');const auth=getAuth(),u=auth.users[normUser(username)];if(!u||u.password!==pass){setErr('Usuário ou senha inválidos. Solicite acesso ao admin.');return}const user={username:u.username,name:u.name||u.username,role:u.role||'student',firstLogin:!!u.firstLogin,loginAt:new Date().toISOString()};localStorage.setItem(LS_USER,JSON.stringify(user));onLogin(user)}async function requestAccess(e){e.preventDefault();setErr('');setMsg('');const nome=first.trim(),sobrenome=last.trim();if(nome.length<2||sobrenome.length<2){setErr('Informe nome e sobrenome.');return}const login=normUser(`${nome}.${sobrenome}`),password=randPass(),req={nome,sobrenome,username:login,password,createdAt:new Date().toISOString()};localStorage.setItem(LS_REQUESTS,JSON.stringify([req,...readJson(LS_REQUESTS,[])].slice(0,50)));const text=`📚 Solicitação de acesso ao Curso SQL\n\nNome: ${nome} ${sobrenome}\nUsuário: ${login}\nSenha inicial: ${password}\n\nAção do admin: liberar/cadastrar e enviar as credenciais ao solicitante.`;try{await notifyTelegram(text);setMsg(`Solicitação enviada ao admin. Usuário sugerido: ${login}`)}catch(ex){setErr(`${ex.message} Usuário sugerido: ${login}. Senha sugerida: ${password}`)}}return <main className="login-page"><section className="login-card"><div className="brand-badge">SQL</div><h1>Curso SQL Offline</h1><p>PWA para iPhone/PC, com teoria em slides, exemplos executáveis, banco local e exercícios com validação.</p><div className="login-switch"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Login</button><button type="button" className={mode==='request'?'active':''} onClick={()=>setMode('request')}>Solicitar acesso</button></div>{mode==='login'?<form onSubmit={submit}><label>Usuário<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" placeholder="nome.sobrenome"/></label><label>Senha<input type="password" value={pass} onChange={e=>setPass(e.target.value)} autoComplete="current-password"/></label>{err&&<div className="error">{err}</div>}{msg&&<div className="ok">{msg}</div>}<button>Entrar</button></form>:<form onSubmit={requestAccess}><label>Nome<input value={first} onChange={e=>setFirst(e.target.value)} autoComplete="given-name"/></label><label>Sobrenome<input value={last} onChange={e=>setLast(e.target.value)} autoComplete="family-name"/></label>{err&&<div className="error">{err}</div>}{msg&&<div className="ok">{msg}</div>}<button>Enviar solicitação ao admin</button></form>}<small>Admin local inicial: <strong>admin</strong> / <strong>admin123</strong>. Troque a senha no primeiro login.</small></section></main>}
function PasswordChange({user,onSave}){const[p1,setP1]=useState(''),[p2,setP2]=useState(''),[err,setErr]=useState('');function submit(e){e.preventDefault();if(p1.length<4){setErr('Senha mínima: 4 caracteres.');return}if(p1!==p2){setErr('As senhas não conferem.');return}onSave(p1)}return <main className="login-page"><section className="login-card"><div className="brand-badge">SQL</div><h1>Alterar senha</h1><p>Primeiro login de <strong>{user.username}</strong>. Defina uma senha nova para continuar.</p><form onSubmit={submit}><label>Nova senha<input type="password" value={p1} onChange={e=>setP1(e.target.value)}/></label><label>Confirmar senha<input type="password" value={p2} onChange={e=>setP2(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button>Salvar senha</button></form></section></main>}
function ProgressRing({value}){return <div className="progress-ring" style={{'--p':`${value}%`}}><span>{value}%</span></div>}
function ResultTable({result}){if(!result)return null;if(result.error)return <div className="error result-box">{result.error}</div>;return <div className="result-box"><div className="result-head">Resultado: {result.rows.length} linha(s)</div><div className="table-wrap"><table><thead><tr>{result.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.slice(0,80).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v===null?'NULL':String(v)}</td>)}</tr>)}</tbody></table></div></div>}
function TheorySlide({slide,SQL,dbSqlText}){const[result,setResult]=useState(null);function run(){try{setResult(runQueryOnFreshDb(SQL,dbSqlText,slide.sql))}catch(e){setResult({error:e.message})}}return <article className="slide-card"><div className="slide-kind">{slide.kind==='example'?'Exemplo executável':'Teoria'}</div><h2>{slide.title}</h2>{slide.points&&<ul>{slide.points.map((p,i)=><li key={i} dangerouslySetInnerHTML={{__html:p}}/>)}</ul>}{slide.sql&&<pre className="sql-block"><code>{slide.sql}</code></pre>}{slide.sql&&<div className="actions"><button disabled={!SQL||!dbSqlText} onClick={run}>Executar exemplo</button></div>}{slide.explanation&&<p className="muted" dangerouslySetInnerHTML={{__html:slide.explanation}}/>}{slide.tip&&<div className="tip" dangerouslySetInnerHTML={{__html:slide.tip}}/>}{slide.warn&&<div className="warn" dangerouslySetInnerHTML={{__html:slide.warn}}/>}{slide.diagram&&<figure className="diagram"><figcaption>{slide.diagram.title}</figcaption><div dangerouslySetInnerHTML={{__html:slide.diagram.svg}}/></figure>}<ResultTable result={result}/></article>}
function Exercise({mod,ex,SQL,dbSqlText,saved,onDone}){const[sql,setSql]=useState(saved?.sql||''),[msg,setMsg]=useState(saved?.done?'✅ Exercício já resolvido.':''),[result,setResult]=useState(null);useEffect(()=>{setSql(saved?.sql||'');setMsg(saved?.done?'✅ Exercício já resolvido.':'');setResult(null)},[mod.id,ex.id]);function run(){setMsg('');try{const check=ex.check?ex.check(sql):{ok:true};if(!check.ok){setMsg(check.msg||'Ajuste a query.');return}const out=runQueryOnFreshDb(SQL,dbSqlText,sql);setResult(out);if(!out.columns.length){setMsg('A query executou, mas não retornou colunas.');return}onDone(makeId(mod.id,ex.id),sql,out);setMsg('✅ Correto. Exercício salvo.')}catch(e){setResult({error:e.message});setMsg('Ajuste a query e execute novamente.')}}return <article className={`exercise-card ${saved?.done?'done':''}`}><div className="exercise-top"><h3>{ex.title}</h3>{saved?.done&&<span>Concluído</span>}</div><p dangerouslySetInnerHTML={{__html:ex.statement}}/><details><summary>Dica</summary><p>{ex.hint}</p></details><textarea value={sql} onChange={e=>setSql(e.target.value)} spellCheck="false" placeholder="Escreva sua query aqui..."/><div className="actions"><button onClick={run} disabled={!SQL||!dbSqlText}>Executar e validar</button><button className="ghost" onClick={()=>setSql(ex.hint||'')}>Usar dica como rascunho</button></div>{msg&&<div className={msg.startsWith('✅')?'ok':'warn'}>{msg}</div>}<ResultTable result={result}/></article>}

function App(){
  const [user,setUser]=useState(()=>readJson(LS_USER,null)),[SQL,setSQL]=useState(null),[dbSqlText,setDbSqlText]=useState(''),[dbStatus,setDbStatus]=useState('Carregando banco offline...'),[modIdx,setModIdx]=useState(0),[tab,setTab]=useState('teoria'),[progress,setProgress]=useState(()=>readJson(LS_PROGRESS,{})),[sideOpen,setSideOpen]=useState(false),[schema,setSchema]=useState([]),[theme,setTheme]=useState(()=>localStorage.getItem(LS_THEME)||'dark'),[fontScale,setFontScale]=useState(()=>Number(localStorage.getItem(LS_FONT)||1)),[expandedModule,setExpandedModule]=useState(0),[touchStart,setTouchStart]=useState(null);
  useEffect(()=>{document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(LS_THEME,theme)},[theme]);
  useEffect(()=>{document.documentElement.style.setProperty('--reader-font',fontScale.toFixed(2));localStorage.setItem(LS_FONT,String(fontScale))},[fontScale]);
  useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});(async()=>{try{const SQLModule=await initSqlJs({locateFile:()=>'/sql-wasm.wasm'});const txt=await fetch('/data/tecnova.sql',{cache:'reload'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()});const db=new SQLModule.Database();db.run(txt);const tables=db.exec("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")[0]?.values.map(r=>r[0])||[];setSchema(tables.map(t=>({table:t,cols:(db.exec(`PRAGMA table_info(${t})`)[0]?.values||[]).map(c=>({name:c[1],type:c[2],pk:c[5]}))})));db.close();setSQL(SQLModule);setDbSqlText(txt);setDbStatus('Banco TechNova carregado localmente.')}catch(e){setDbStatus('Erro ao carregar banco: '+e.message+' — use Recarregar BD.')}})()},[]);
  if(!user)return <Login onLogin={setUser}/>;
  function changePassword(newPass){const auth=getAuth(),u=auth.users[user.username];if(u){u.password=newPass;u.firstLogin=false;saveAuth(auth)}const nu={...user,firstLogin:false};localStorage.setItem(LS_USER,JSON.stringify(nu));setUser(nu)}
  if(user.firstLogin)return <PasswordChange user={user} onSave={changePassword}/>;
  const mod=COURSE[modIdx],total=COURSE.reduce((a,m)=>a+(m.exercises?.length||0),0),done=Object.values(progress).filter(v=>v?.done).length,percentage=pct(done,total),modDone=(mod.exercises||[]).filter(e=>progress[makeId(mod.id,e.id)]?.done).length;
  function markDone(id,sql,out){const next={...progress,[id]:{done:true,sql,doneAt:new Date().toISOString(),preview:{columns:out.columns,rows:out.rows.slice(0,5)}}};setProgress(next);saveProgress(next)}
  function resetModuleProgress(targetIdx=modIdx){const target=COURSE[targetIdx]||mod;if(confirm(`Limpar progresso apenas do módulo ${target.title}?`)){const next={...progress};(target.exercises||[]).forEach(e=>delete next[makeId(target.id,e.id)]);setProgress(next);saveProgress(next)}}
  async function resetDb(){if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations().catch(()=>[]);await Promise.all(regs.map(r=>r.update().catch(()=>null)))}location.reload()}
  function availableTabs(idx){const m=COURSE[idx];const tabs=['teoria'];if((m.slides||[]).some(s=>s.kind==='example'))tabs.push('exemplos');if((m.exercises||[]).length)tabs.push('exercicios');return tabs}
  function moveStep(dir){if(tab==='db'||tab==='admin'||tab==='lab')return;const tabs=availableTabs(modIdx);const ti=tabs.indexOf(tab);if(dir>0){if(ti<tabs.length-1){setTab(tabs[ti+1]);return}if(modIdx<COURSE.length-1){setModIdx(modIdx+1);setExpandedModule(modIdx+1);setTab('teoria')}}else{if(ti>0){setTab(tabs[ti-1]);return}if(modIdx>0){const prev=modIdx-1,pt=availableTabs(prev);setModIdx(prev);setExpandedModule(prev);setTab(pt[pt.length-1]||'teoria')}}}
  function handleTouchStart(e){if(e.target.closest('textarea,input,button,.table-wrap'))return;const t=e.touches?.[0];if(t)setTouchStart({x:t.clientX,y:t.clientY})}
  function handleTouchEnd(e){if(!touchStart)return;const t=e.changedTouches?.[0];if(!t)return;const dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;setTouchStart(null);if(Math.abs(dx)>90&&Math.abs(dx)>Math.abs(dy)*1.6)moveStep(dx<0?1:-1)}
  function logout(){localStorage.removeItem(LS_USER);location.reload()}
  return <div className={`app-shell ${sideOpen?'side-open':'side-closed'}`}>
    <header className="app-taskbar"><button className="taskbar-menu" type="button" aria-label={sideOpen?'Fechar menu':'Abrir menu'} onClick={()=>setSideOpen(v=>!v)}><span>{sideOpen?'×':'☰'}</span></button><strong>Curso SQL Offline</strong><ProgressRing value={percentage}/><div className="font-controls"><button type="button" onClick={()=>setFontScale(v=>Math.max(.92,Number((v-.06).toFixed(2))))}>A−</button><button type="button" onClick={()=>setFontScale(1)}>A</button><button type="button" onClick={()=>setFontScale(v=>Math.min(1.28,Number((v+.06).toFixed(2))))}>A+</button></div></header>
    <button className="sidebar-backdrop" type="button" onClick={()=>setSideOpen(false)}/>
    <aside className="sidebar"><div className="side-brand"><div className="brand-badge small">SQL</div><div><strong>Curso SQL</strong><small>Offline / PWA</small></div></div><div className="user-panel"><div><b>{user.name}</b><small>{user.username} · {user.role==='admin'?'Admin':'Aluno'}</small><button className="ghost mini" onClick={logout}>Sair</button></div></div><div className="theme-toggle"><button className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}>🌙 Dark</button><button className={theme==='light'?'active':''} onClick={()=>setTheme('light')}>☀️ Light</button></div><nav className="module-nav">{COURSE.map((m,i)=>{const d=(m.exercises||[]).filter(e=>progress[makeId(m.id,e.id)]?.done).length,active=i===modIdx&&tab!=='db'&&tab!=='admin'&&tab!=='lab',open=expandedModule===i;return <div key={m.id} className={`module-group ${open?'open':''}`}><button className={`module-head ${active?'active':''}`} onClick={()=>{setExpandedModule(open?-1:i);setModIdx(i);if(tab==='db'||tab==='admin'||tab==='lab')setTab('teoria')}}><span>{m.icon}</span><b>{m.title}</b><em>{d}/{m.exercises?.length||0}</em><i>{open?'−':'+'}</i></button>{open&&<div className="module-submenu"><button className={active&&tab==='teoria'?'active':''} onClick={()=>{setModIdx(i);setTab('teoria');setSideOpen(false)}}>📘 Teoria</button><button className={active&&tab==='exemplos'?'active':''} onClick={()=>{setModIdx(i);setTab('exemplos');setSideOpen(false)}}>▶️ Exemplos</button>{(m.exercises||[]).length>0&&<button className={active&&tab==='exercicios'?'active':''} onClick={()=>{setModIdx(i);setTab('exercicios');setSideOpen(false)}}>🧪 Exercícios</button>}<button onClick={()=>{setModIdx(i);resetModuleProgress(i)}}>🧹 Limpar progresso</button></div>}</div>})}<div className="resource-menu"><strong>Ferramentas</strong><button className={tab==='db'?'active':''} onClick={()=>{setTab('db');setSideOpen(false)}}>🗄️ DB interno</button><button onClick={resetDb}>🔄 Recarregar DB interno</button><button className={tab==='lab'?'active':''} onClick={()=>{setTab('lab');setSideOpen(false)}}>💻 Laboratório livre</button>{user.role==='admin'&&<button className={tab==='admin'?'active':''} onClick={()=>{setTab('admin');setSideOpen(false)}}>🔐 Admin / usuários</button>}<small>{dbStatus}</small></div></nav></aside>
    <main className="content" onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}><header className="topbar"><div><h1>{tab==='db'?'Banco interno TechNova':tab==='admin'?'Administração de usuários':tab==='lab'?'Laboratório livre':tab==='exemplos'?'Exemplos — '+mod.title:tab==='exercicios'?'Exercícios — '+mod.title:mod.title}</h1><p>{tab==='db'?'Tabelas, colunas e prévia dos dados usados no curso.':tab==='admin'?'Cadastre usuários com login nome.sobrenome e senha inicial.':tab==='lab'?'Área livre para testar SELECTs sem poluir os módulos.':mod.objective}</p></div></header>{tab==='teoria'&&<section className="slides">{mod.slides?.filter(s=>s.kind!=='example').map((s,i)=><TheorySlide slide={s} key={i} SQL={SQL} dbSqlText={dbSqlText}/>)}</section>}{tab==='exemplos'&&<section className="slides">{mod.slides?.filter(s=>s.kind==='example').map((s,i)=><TheorySlide slide={s} key={i} SQL={SQL} dbSqlText={dbSqlText}/>)}</section>}{tab==='exercicios'&&<section className="exercises">{(!SQL||!dbSqlText)&&<div className="warn">Aguarde o banco carregar.</div>}{SQL&&dbSqlText&&(mod.exercises||[]).length===0&&<div className="tip">Este módulo é apenas conceitual. Arraste para o próximo módulo.</div>}{SQL&&dbSqlText&&mod.exercises?.map(ex=><Exercise key={ex.id} mod={mod} ex={ex} SQL={SQL} dbSqlText={dbSqlText} saved={progress[makeId(mod.id,ex.id)]} onDone={markDone}/>)}</section>}{tab==='lab'&&<Lab SQL={SQL} dbSqlText={dbSqlText}/>} {tab==='db'&&<DbExplorer schema={schema} SQL={SQL} dbSqlText={dbSqlText}/>} {tab==='admin'&&<AdminPanel/>}</main>
  </div>}
function Lab({SQL,dbSqlText}){const[sql,setSql]=useState('SELECT * FROM funcionarios LIMIT 10;'),[result,setResult]=useState(null);function run(){try{setResult(runQueryOnFreshDb(SQL,dbSqlText,sql))}catch(e){setResult({error:e.message})}}return <section className="exercise-card"><h2>Laboratório livre</h2><p className="muted">Use para testar SELECTs no banco TechNova. Alterações ficam bloqueadas.</p><textarea value={sql} onChange={e=>setSql(e.target.value)} spellCheck="false"/><div className="actions"><button disabled={!SQL||!dbSqlText} onClick={run}>Executar SQL</button></div><ResultTable result={result}/></section>}
function DbExplorer({schema,SQL,dbSqlText}){const[result,setResult]=useState(null);function preview(t){try{setResult(runQueryOnFreshDb(SQL,dbSqlText,`SELECT * FROM ${t} LIMIT 20;`))}catch(e){setResult({error:e.message})}}return <section className="db-grid"><div className="schema-list">{schema.map(t=><article className="schema-card" key={t.table}><div><h3>{t.table}</h3><button onClick={()=>preview(t.table)} disabled={!SQL}>Ver 20 linhas</button></div><ul>{t.cols.map(c=><li key={c.name}><code>{c.name}</code><span>{c.type||'sem tipo'}{c.pk?' · PK':''}</span></li>)}</ul></article>)}</div><ResultTable result={result}/></section>}
function AdminPanel(){const[auth,setAuth]=useState(getAuth()),[reqs]=useState(readJson(LS_REQUESTS,[])),[nome,setNome]=useState(''),[sobrenome,setSobrenome]=useState(''),[senha,setSenha]=useState(randPass()),[msg,setMsg]=useState('');function addUser(e){e.preventDefault();const username=normUser(`${nome}.${sobrenome}`);if(!username.includes('.')){setMsg('Informe nome e sobrenome.');return}const next={...auth,users:{...auth.users,[username]:{username,password:senha,role:'student',firstLogin:true,name:`${nome.trim()} ${sobrenome.trim()}`}}};saveAuth(next);setAuth(next);setMsg(`Usuário criado: ${username} / ${senha}`);setSenha(randPass())}function addFromReq(r){const username=r.username,next={...auth,users:{...auth.users,[username]:{username,password:r.password,role:'student',firstLogin:true,name:`${r.nome} ${r.sobrenome}`}}};saveAuth(next);setAuth(next);setMsg(`Usuário liberado: ${username} / ${r.password}`)}return <section className="admin-grid"><article className="exercise-card"><h2>Cadastrar usuário</h2><form onSubmit={addUser} className="admin-form"><label>Nome<input value={nome} onChange={e=>setNome(e.target.value)}/></label><label>Sobrenome<input value={sobrenome} onChange={e=>setSobrenome(e.target.value)}/></label><label>Senha inicial<input value={senha} onChange={e=>setSenha(e.target.value)}/></label><button>Criar usuário local</button></form>{msg&&<div className="ok">{msg}</div>}<p className="muted">Login no padrão <code>nome.sobrenome</code>. O usuário troca a senha no primeiro acesso.</p></article><article className="exercise-card"><h2>Solicitações deste dispositivo</h2>{reqs.length===0&&<p className="muted">Nenhuma solicitação registrada localmente.</p>}{reqs.map((r,i)=><div className="request-card" key={i}><b>{r.nome} {r.sobrenome}</b><code>{r.username}</code><span>{r.password}</span><button onClick={()=>addFromReq(r)}>Liberar</button></div>)}</article><article className="exercise-card"><h2>Usuários locais</h2><div className="users-list">{Object.values(auth.users).map(u=><div key={u.username}><b>{u.username}</b><span>{u.role} {u.firstLogin?'· troca senha pendente':''}</span></div>)}</div></article></section>}
createRoot(document.getElementById('root')).render(<App/>);
